/**
 * generated by Xtext 2.25.0
 */
package fr.irisa.dslCsv.tests;

import fr.irisa.dslCsv.ConstNat;
import fr.irisa.dslCsv.DslCsvFactory;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Const Nat</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class ConstNatTest extends BaseExpressionTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(ConstNatTest.class);
	}

	/**
	 * Constructs a new Const Nat test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ConstNatTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Const Nat test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected ConstNat getFixture() {
		return (ConstNat)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(DslCsvFactory.eINSTANCE.createConstNat());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //ConstNatTest
