/**
 * generated by Xtext 2.25.0
 */
package fr.irisa.dslCsv.tests;

import fr.irisa.dslCsv.Count;
import fr.irisa.dslCsv.DslCsvFactory;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Count</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class CountTest extends FuncCallTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(CountTest.class);
	}

	/**
	 * Constructs a new Count test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public CountTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Count test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected Count getFixture() {
		return (Count)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(DslCsvFactory.eINSTANCE.createCount());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //CountTest
