/*
 * generated by Xtext 2.25.0
 */
package fr.irisa.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDslCsvScopeProvider extends DelegatingScopeProvider {
}
