/*
 * generated by Xtext 2.25.0
 */
package fr.irisa;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class DslCsvStandaloneSetup extends DslCsvStandaloneSetupGenerated {

	public static void doSetup() {
		new DslCsvStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
