/*
 * generated by Xtext 2.25.0
 */
package fr.irisa.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.irisa.DslCsvRuntimeModule;
import fr.irisa.DslCsvStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DslCsvIdeSetup extends DslCsvStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DslCsvRuntimeModule(), new DslCsvIdeModule()));
	}
	
}
