/*
 * generated by Xtext 2.25.0
 */
package fr.irisa.dslCsv.tests.interpreter

import com.google.inject.Inject
import fr.irisa.dslCsv.Program
import fr.irisa.generator.ASTtoInterpretation
import fr.irisa.generator.InterpretationContext
import fr.irisa.tests.DslCsvInjectorProvider
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(DslCsvInjectorProvider)
class AssignInterpretationTest {
	@Inject
	ParseHelper<Program> parseHelper
	
	@Test
	def void CompleteTest() {
		val result = parseHelper.parse('''
			c=1*2;
			a=b=c
		''')
		val errors = result.eResource.errors
		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
		try {
			val context = new InterpretationContext()
			val i = (ASTtoInterpretation.eval((result as Program).expr, context)) as InterpretationContext
			Assertions.assertEquals(context.variables.get("b"), 2.0)
			Assertions.assertEquals(context.variables.get("c"), 2.0)
			Assertions.assertEquals(context.variables.get("a"), 2.0)
		} catch(ClassCastException exc) {
			Assertions.fail("Wrong type in tests")
		} 
	}
}
