/**
 * generated by Xtext 2.25.0
 */
package fr.irisa.dslCsv;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Base Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.irisa.dslCsv.DslCsvPackage#getBaseExpression()
 * @model
 * @generated
 */
public interface BaseExpression extends EObject
{
} // BaseExpression
