/**
 * generated by Xtext 2.25.0
 */
package fr.irisa.dslCsv;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comp Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.irisa.dslCsv.CompExpression#getLeft <em>Left</em>}</li>
 *   <li>{@link fr.irisa.dslCsv.CompExpression#getOp <em>Op</em>}</li>
 *   <li>{@link fr.irisa.dslCsv.CompExpression#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see fr.irisa.dslCsv.DslCsvPackage#getCompExpression()
 * @model
 * @generated
 */
public interface CompExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(ArithExpression)
   * @see fr.irisa.dslCsv.DslCsvPackage#getCompExpression_Left()
   * @model containment="true"
   * @generated
   */
  ArithExpression getLeft();

  /**
   * Sets the value of the '{@link fr.irisa.dslCsv.CompExpression#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(ArithExpression value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see fr.irisa.dslCsv.DslCsvPackage#getCompExpression_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link fr.irisa.dslCsv.CompExpression#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(CompExpression)
   * @see fr.irisa.dslCsv.DslCsvPackage#getCompExpression_Right()
   * @model containment="true"
   * @generated
   */
  CompExpression getRight();

  /**
   * Sets the value of the '{@link fr.irisa.dslCsv.CompExpression#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(CompExpression value);

} // CompExpression
