/**
 * generated by Xtext 2.25.0
 */
package fr.irisa.dslCsv;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Const Str</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.irisa.dslCsv.ConstStr#getConstStr <em>Const Str</em>}</li>
 * </ul>
 *
 * @see fr.irisa.dslCsv.DslCsvPackage#getConstStr()
 * @model
 * @generated
 */
public interface ConstStr extends BaseExpression
{
  /**
   * Returns the value of the '<em><b>Const Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Const Str</em>' attribute.
   * @see #setConstStr(String)
   * @see fr.irisa.dslCsv.DslCsvPackage#getConstStr_ConstStr()
   * @model
   * @generated
   */
  String getConstStr();

  /**
   * Sets the value of the '{@link fr.irisa.dslCsv.ConstStr#getConstStr <em>Const Str</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Const Str</em>' attribute.
   * @see #getConstStr()
   * @generated
   */
  void setConstStr(String value);

} // ConstStr
