/**
 * generated by Xtext 2.25.0
 */
package fr.irisa.dslCsv;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Const Nat</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.irisa.dslCsv.ConstNat#getConstNat <em>Const Nat</em>}</li>
 * </ul>
 *
 * @see fr.irisa.dslCsv.DslCsvPackage#getConstNat()
 * @model
 * @generated
 */
public interface ConstNat extends BaseExpression
{
  /**
   * Returns the value of the '<em><b>Const Nat</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Const Nat</em>' attribute.
   * @see #setConstNat(int)
   * @see fr.irisa.dslCsv.DslCsvPackage#getConstNat_ConstNat()
   * @model
   * @generated
   */
  int getConstNat();

  /**
   * Sets the value of the '{@link fr.irisa.dslCsv.ConstNat#getConstNat <em>Const Nat</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Const Nat</em>' attribute.
   * @see #getConstNat()
   * @generated
   */
  void setConstNat(int value);

} // ConstNat
