/**
 * generated by Xtext 2.25.0
 */
package fr.irisa.dslCsv;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Const Vector</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.irisa.dslCsv.ConstVector#getConstVector <em>Const Vector</em>}</li>
 * </ul>
 *
 * @see fr.irisa.dslCsv.DslCsvPackage#getConstVector()
 * @model
 * @generated
 */
public interface ConstVector extends BaseExpression
{
  /**
   * Returns the value of the '<em><b>Const Vector</b></em>' containment reference list.
   * The list contents are of type {@link fr.irisa.dslCsv.Expression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Const Vector</em>' containment reference list.
   * @see fr.irisa.dslCsv.DslCsvPackage#getConstVector_ConstVector()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getConstVector();

} // ConstVector
