/**
 * generated by Xtext 2.25.0
 */
package fr.irisa.dslCsv;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.irisa.dslCsv.DslCsvFactory
 * @model kind="package"
 * @generated
 */
public interface DslCsvPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dslCsv";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.irisa.fr/DslCsv";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dslCsv";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DslCsvPackage eINSTANCE = fr.irisa.dslCsv.impl.DslCsvPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.ProgramImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__EXPR = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.ExpressionImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 1;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.AssignImpl <em>Assign</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.AssignImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getAssign()
   * @generated
   */
  int ASSIGN = 2;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGN__VAR = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGN__VAL = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Assign</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGN_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.NopImpl <em>Nop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.NopImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getNop()
   * @generated
   */
  int NOP = 3;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOP__EXPR = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Nop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOP_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.LogicalExpressionImpl <em>Logical Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.LogicalExpressionImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getLogicalExpression()
   * @generated
   */
  int LOGICAL_EXPRESSION = 4;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGICAL_EXPRESSION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGICAL_EXPRESSION__OP = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGICAL_EXPRESSION__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Logical Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGICAL_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.CompExpressionImpl <em>Comp Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.CompExpressionImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getCompExpression()
   * @generated
   */
  int COMP_EXPRESSION = 5;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMP_EXPRESSION__LEFT = 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMP_EXPRESSION__OP = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMP_EXPRESSION__RIGHT = 2;

  /**
   * The number of structural features of the '<em>Comp Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMP_EXPRESSION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.ArithExpressionImpl <em>Arith Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.ArithExpressionImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getArithExpression()
   * @generated
   */
  int ARITH_EXPRESSION = 6;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_EXPRESSION__LEFT = 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_EXPRESSION__OP = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_EXPRESSION__RIGHT = 2;

  /**
   * The number of structural features of the '<em>Arith Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARITH_EXPRESSION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.SubExpressionImpl <em>Sub Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.SubExpressionImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getSubExpression()
   * @generated
   */
  int SUB_EXPRESSION = 7;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_EXPRESSION__LEFT = 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_EXPRESSION__OP = 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_EXPRESSION__RIGHT = 2;

  /**
   * The number of structural features of the '<em>Sub Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUB_EXPRESSION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.BaseExpressionImpl <em>Base Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.BaseExpressionImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getBaseExpression()
   * @generated
   */
  int BASE_EXPRESSION = 8;

  /**
   * The number of structural features of the '<em>Base Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASE_EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.VarImpl <em>Var</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.VarImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getVar()
   * @generated
   */
  int VAR = 9;

  /**
   * The feature id for the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR__VAR = BASE_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Var</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_FEATURE_COUNT = BASE_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.ConstNatImpl <em>Const Nat</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.ConstNatImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getConstNat()
   * @generated
   */
  int CONST_NAT = 10;

  /**
   * The feature id for the '<em><b>Const Nat</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONST_NAT__CONST_NAT = BASE_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Const Nat</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONST_NAT_FEATURE_COUNT = BASE_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.ConstStrImpl <em>Const Str</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.ConstStrImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getConstStr()
   * @generated
   */
  int CONST_STR = 11;

  /**
   * The feature id for the '<em><b>Const Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONST_STR__CONST_STR = BASE_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Const Str</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONST_STR_FEATURE_COUNT = BASE_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.ParenthesisImpl <em>Parenthesis</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.ParenthesisImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getParenthesis()
   * @generated
   */
  int PARENTHESIS = 12;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARENTHESIS__EXPR = BASE_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Parenthesis</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARENTHESIS_FEATURE_COUNT = BASE_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.ConstVectorImpl <em>Const Vector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.ConstVectorImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getConstVector()
   * @generated
   */
  int CONST_VECTOR = 13;

  /**
   * The feature id for the '<em><b>Const Vector</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONST_VECTOR__CONST_VECTOR = BASE_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Const Vector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONST_VECTOR_FEATURE_COUNT = BASE_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.FuncCallImpl <em>Func Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.FuncCallImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getFuncCall()
   * @generated
   */
  int FUNC_CALL = 14;

  /**
   * The number of structural features of the '<em>Func Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNC_CALL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.CountImpl <em>Count</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.CountImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getCount()
   * @generated
   */
  int COUNT = 15;

  /**
   * The feature id for the '<em><b>Vector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COUNT__VECTOR = FUNC_CALL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Count</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COUNT_FEATURE_COUNT = FUNC_CALL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.SortImpl <em>Sort</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.SortImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getSort()
   * @generated
   */
  int SORT = 16;

  /**
   * The feature id for the '<em><b>File</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SORT__FILE = FUNC_CALL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Criterion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SORT__CRITERION = FUNC_CALL_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Sort</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SORT_FEATURE_COUNT = FUNC_CALL_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.DimImpl <em>Dim</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.DimImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getDim()
   * @generated
   */
  int DIM = 17;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIM__EXPR = FUNC_CALL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Dim</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIM_FEATURE_COUNT = FUNC_CALL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.PrintImpl <em>Print</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.PrintImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getPrint()
   * @generated
   */
  int PRINT = 18;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT__EXPR = FUNC_CALL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Print</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT_FEATURE_COUNT = FUNC_CALL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.FeaturesImpl <em>Features</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.FeaturesImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getFeatures()
   * @generated
   */
  int FEATURES = 19;

  /**
   * The feature id for the '<em><b>File</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURES__FILE = FUNC_CALL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Features</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FEATURES_FEATURE_COUNT = FUNC_CALL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.RowImpl <em>Row</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.RowImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getRow()
   * @generated
   */
  int ROW = 20;

  /**
   * The feature id for the '<em><b>File</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW__FILE = FUNC_CALL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Vector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW__VECTOR = FUNC_CALL_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Row</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_FEATURE_COUNT = FUNC_CALL_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.ColumnImpl <em>Column</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.ColumnImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getColumn()
   * @generated
   */
  int COLUMN = 21;

  /**
   * The feature id for the '<em><b>File</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN__FILE = FUNC_CALL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Column Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN__COLUMN_NAME = FUNC_CALL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Vector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN__VECTOR = FUNC_CALL_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Column</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_FEATURE_COUNT = FUNC_CALL_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.ProductImpl <em>Product</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.ProductImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getProduct()
   * @generated
   */
  int PRODUCT = 22;

  /**
   * The feature id for the '<em><b>Vector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT__VECTOR = FUNC_CALL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Product</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_FEATURE_COUNT = FUNC_CALL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.SumImpl <em>Sum</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.SumImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getSum()
   * @generated
   */
  int SUM = 23;

  /**
   * The feature id for the '<em><b>Vector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUM__VECTOR = FUNC_CALL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Sum</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUM_FEATURE_COUNT = FUNC_CALL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.MeanImpl <em>Mean</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.MeanImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getMean()
   * @generated
   */
  int MEAN = 24;

  /**
   * The feature id for the '<em><b>Vector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEAN__VECTOR = FUNC_CALL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Mean</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEAN_FEATURE_COUNT = FUNC_CALL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.FilterImpl <em>Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.FilterImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getFilter()
   * @generated
   */
  int FILTER = 25;

  /**
   * The feature id for the '<em><b>File</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER__FILE = FUNC_CALL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Cond</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER__COND = FUNC_CALL_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_FEATURE_COUNT = FUNC_CALL_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.UnselectImpl <em>Unselect</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.UnselectImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getUnselect()
   * @generated
   */
  int UNSELECT = 26;

  /**
   * The feature id for the '<em><b>File</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNSELECT__FILE = FUNC_CALL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Features</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNSELECT__FEATURES = FUNC_CALL_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Unselect</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNSELECT_FEATURE_COUNT = FUNC_CALL_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.SelectImpl <em>Select</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.SelectImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getSelect()
   * @generated
   */
  int SELECT = 27;

  /**
   * The feature id for the '<em><b>File</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__FILE = FUNC_CALL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Features</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__FEATURES = FUNC_CALL_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Select</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_FEATURE_COUNT = FUNC_CALL_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.SaveImpl <em>Save</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.SaveImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getSave()
   * @generated
   */
  int SAVE = 28;

  /**
   * The feature id for the '<em><b>Filename</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAVE__FILENAME = FUNC_CALL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>File</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAVE__FILE = FUNC_CALL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Sep</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAVE__SEP = FUNC_CALL_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Save Header</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAVE__SAVE_HEADER = FUNC_CALL_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Save ID</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAVE__SAVE_ID = FUNC_CALL_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Save</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAVE_FEATURE_COUNT = FUNC_CALL_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link fr.irisa.dslCsv.impl.AcquireImpl <em>Acquire</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.irisa.dslCsv.impl.AcquireImpl
   * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getAcquire()
   * @generated
   */
  int ACQUIRE = 29;

  /**
   * The feature id for the '<em><b>Path</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACQUIRE__PATH = FUNC_CALL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Sep</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACQUIRE__SEP = FUNC_CALL_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Has Header</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACQUIRE__HAS_HEADER = FUNC_CALL_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Acquire</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACQUIRE_FEATURE_COUNT = FUNC_CALL_FEATURE_COUNT + 3;


  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see fr.irisa.dslCsv.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference list '{@link fr.irisa.dslCsv.Program#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expr</em>'.
   * @see fr.irisa.dslCsv.Program#getExpr()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Expr();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see fr.irisa.dslCsv.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.Assign <em>Assign</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assign</em>'.
   * @see fr.irisa.dslCsv.Assign
   * @generated
   */
  EClass getAssign();

  /**
   * Returns the meta object for the attribute '{@link fr.irisa.dslCsv.Assign#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var</em>'.
   * @see fr.irisa.dslCsv.Assign#getVar()
   * @see #getAssign()
   * @generated
   */
  EAttribute getAssign_Var();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Assign#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Val</em>'.
   * @see fr.irisa.dslCsv.Assign#getVal()
   * @see #getAssign()
   * @generated
   */
  EReference getAssign_Val();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.Nop <em>Nop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nop</em>'.
   * @see fr.irisa.dslCsv.Nop
   * @generated
   */
  EClass getNop();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Nop#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see fr.irisa.dslCsv.Nop#getExpr()
   * @see #getNop()
   * @generated
   */
  EReference getNop_Expr();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.LogicalExpression <em>Logical Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Logical Expression</em>'.
   * @see fr.irisa.dslCsv.LogicalExpression
   * @generated
   */
  EClass getLogicalExpression();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.LogicalExpression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see fr.irisa.dslCsv.LogicalExpression#getLeft()
   * @see #getLogicalExpression()
   * @generated
   */
  EReference getLogicalExpression_Left();

  /**
   * Returns the meta object for the attribute '{@link fr.irisa.dslCsv.LogicalExpression#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see fr.irisa.dslCsv.LogicalExpression#getOp()
   * @see #getLogicalExpression()
   * @generated
   */
  EAttribute getLogicalExpression_Op();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.LogicalExpression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see fr.irisa.dslCsv.LogicalExpression#getRight()
   * @see #getLogicalExpression()
   * @generated
   */
  EReference getLogicalExpression_Right();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.CompExpression <em>Comp Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comp Expression</em>'.
   * @see fr.irisa.dslCsv.CompExpression
   * @generated
   */
  EClass getCompExpression();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.CompExpression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see fr.irisa.dslCsv.CompExpression#getLeft()
   * @see #getCompExpression()
   * @generated
   */
  EReference getCompExpression_Left();

  /**
   * Returns the meta object for the attribute '{@link fr.irisa.dslCsv.CompExpression#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see fr.irisa.dslCsv.CompExpression#getOp()
   * @see #getCompExpression()
   * @generated
   */
  EAttribute getCompExpression_Op();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.CompExpression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see fr.irisa.dslCsv.CompExpression#getRight()
   * @see #getCompExpression()
   * @generated
   */
  EReference getCompExpression_Right();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.ArithExpression <em>Arith Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Arith Expression</em>'.
   * @see fr.irisa.dslCsv.ArithExpression
   * @generated
   */
  EClass getArithExpression();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.ArithExpression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see fr.irisa.dslCsv.ArithExpression#getLeft()
   * @see #getArithExpression()
   * @generated
   */
  EReference getArithExpression_Left();

  /**
   * Returns the meta object for the attribute '{@link fr.irisa.dslCsv.ArithExpression#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see fr.irisa.dslCsv.ArithExpression#getOp()
   * @see #getArithExpression()
   * @generated
   */
  EAttribute getArithExpression_Op();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.ArithExpression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see fr.irisa.dslCsv.ArithExpression#getRight()
   * @see #getArithExpression()
   * @generated
   */
  EReference getArithExpression_Right();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.SubExpression <em>Sub Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sub Expression</em>'.
   * @see fr.irisa.dslCsv.SubExpression
   * @generated
   */
  EClass getSubExpression();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.SubExpression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see fr.irisa.dslCsv.SubExpression#getLeft()
   * @see #getSubExpression()
   * @generated
   */
  EReference getSubExpression_Left();

  /**
   * Returns the meta object for the attribute '{@link fr.irisa.dslCsv.SubExpression#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see fr.irisa.dslCsv.SubExpression#getOp()
   * @see #getSubExpression()
   * @generated
   */
  EAttribute getSubExpression_Op();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.SubExpression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see fr.irisa.dslCsv.SubExpression#getRight()
   * @see #getSubExpression()
   * @generated
   */
  EReference getSubExpression_Right();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.BaseExpression <em>Base Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Base Expression</em>'.
   * @see fr.irisa.dslCsv.BaseExpression
   * @generated
   */
  EClass getBaseExpression();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.Var <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var</em>'.
   * @see fr.irisa.dslCsv.Var
   * @generated
   */
  EClass getVar();

  /**
   * Returns the meta object for the attribute '{@link fr.irisa.dslCsv.Var#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Var</em>'.
   * @see fr.irisa.dslCsv.Var#getVar()
   * @see #getVar()
   * @generated
   */
  EAttribute getVar_Var();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.ConstNat <em>Const Nat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Const Nat</em>'.
   * @see fr.irisa.dslCsv.ConstNat
   * @generated
   */
  EClass getConstNat();

  /**
   * Returns the meta object for the attribute '{@link fr.irisa.dslCsv.ConstNat#getConstNat <em>Const Nat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Const Nat</em>'.
   * @see fr.irisa.dslCsv.ConstNat#getConstNat()
   * @see #getConstNat()
   * @generated
   */
  EAttribute getConstNat_ConstNat();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.ConstStr <em>Const Str</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Const Str</em>'.
   * @see fr.irisa.dslCsv.ConstStr
   * @generated
   */
  EClass getConstStr();

  /**
   * Returns the meta object for the attribute '{@link fr.irisa.dslCsv.ConstStr#getConstStr <em>Const Str</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Const Str</em>'.
   * @see fr.irisa.dslCsv.ConstStr#getConstStr()
   * @see #getConstStr()
   * @generated
   */
  EAttribute getConstStr_ConstStr();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.Parenthesis <em>Parenthesis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parenthesis</em>'.
   * @see fr.irisa.dslCsv.Parenthesis
   * @generated
   */
  EClass getParenthesis();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Parenthesis#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see fr.irisa.dslCsv.Parenthesis#getExpr()
   * @see #getParenthesis()
   * @generated
   */
  EReference getParenthesis_Expr();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.ConstVector <em>Const Vector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Const Vector</em>'.
   * @see fr.irisa.dslCsv.ConstVector
   * @generated
   */
  EClass getConstVector();

  /**
   * Returns the meta object for the containment reference list '{@link fr.irisa.dslCsv.ConstVector#getConstVector <em>Const Vector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Const Vector</em>'.
   * @see fr.irisa.dslCsv.ConstVector#getConstVector()
   * @see #getConstVector()
   * @generated
   */
  EReference getConstVector_ConstVector();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.FuncCall <em>Func Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Func Call</em>'.
   * @see fr.irisa.dslCsv.FuncCall
   * @generated
   */
  EClass getFuncCall();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.Count <em>Count</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Count</em>'.
   * @see fr.irisa.dslCsv.Count
   * @generated
   */
  EClass getCount();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Count#getVector <em>Vector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Vector</em>'.
   * @see fr.irisa.dslCsv.Count#getVector()
   * @see #getCount()
   * @generated
   */
  EReference getCount_Vector();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.Sort <em>Sort</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sort</em>'.
   * @see fr.irisa.dslCsv.Sort
   * @generated
   */
  EClass getSort();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Sort#getFile <em>File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>File</em>'.
   * @see fr.irisa.dslCsv.Sort#getFile()
   * @see #getSort()
   * @generated
   */
  EReference getSort_File();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Sort#getCriterion <em>Criterion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Criterion</em>'.
   * @see fr.irisa.dslCsv.Sort#getCriterion()
   * @see #getSort()
   * @generated
   */
  EReference getSort_Criterion();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.Dim <em>Dim</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dim</em>'.
   * @see fr.irisa.dslCsv.Dim
   * @generated
   */
  EClass getDim();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Dim#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see fr.irisa.dslCsv.Dim#getExpr()
   * @see #getDim()
   * @generated
   */
  EReference getDim_Expr();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.Print <em>Print</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Print</em>'.
   * @see fr.irisa.dslCsv.Print
   * @generated
   */
  EClass getPrint();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Print#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see fr.irisa.dslCsv.Print#getExpr()
   * @see #getPrint()
   * @generated
   */
  EReference getPrint_Expr();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.Features <em>Features</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Features</em>'.
   * @see fr.irisa.dslCsv.Features
   * @generated
   */
  EClass getFeatures();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Features#getFile <em>File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>File</em>'.
   * @see fr.irisa.dslCsv.Features#getFile()
   * @see #getFeatures()
   * @generated
   */
  EReference getFeatures_File();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.Row <em>Row</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Row</em>'.
   * @see fr.irisa.dslCsv.Row
   * @generated
   */
  EClass getRow();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Row#getFile <em>File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>File</em>'.
   * @see fr.irisa.dslCsv.Row#getFile()
   * @see #getRow()
   * @generated
   */
  EReference getRow_File();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Row#getVector <em>Vector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Vector</em>'.
   * @see fr.irisa.dslCsv.Row#getVector()
   * @see #getRow()
   * @generated
   */
  EReference getRow_Vector();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.Column <em>Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Column</em>'.
   * @see fr.irisa.dslCsv.Column
   * @generated
   */
  EClass getColumn();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Column#getFile <em>File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>File</em>'.
   * @see fr.irisa.dslCsv.Column#getFile()
   * @see #getColumn()
   * @generated
   */
  EReference getColumn_File();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Column#getColumnName <em>Column Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Column Name</em>'.
   * @see fr.irisa.dslCsv.Column#getColumnName()
   * @see #getColumn()
   * @generated
   */
  EReference getColumn_ColumnName();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Column#getVector <em>Vector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Vector</em>'.
   * @see fr.irisa.dslCsv.Column#getVector()
   * @see #getColumn()
   * @generated
   */
  EReference getColumn_Vector();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.Product <em>Product</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Product</em>'.
   * @see fr.irisa.dslCsv.Product
   * @generated
   */
  EClass getProduct();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Product#getVector <em>Vector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Vector</em>'.
   * @see fr.irisa.dslCsv.Product#getVector()
   * @see #getProduct()
   * @generated
   */
  EReference getProduct_Vector();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.Sum <em>Sum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sum</em>'.
   * @see fr.irisa.dslCsv.Sum
   * @generated
   */
  EClass getSum();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Sum#getVector <em>Vector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Vector</em>'.
   * @see fr.irisa.dslCsv.Sum#getVector()
   * @see #getSum()
   * @generated
   */
  EReference getSum_Vector();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.Mean <em>Mean</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mean</em>'.
   * @see fr.irisa.dslCsv.Mean
   * @generated
   */
  EClass getMean();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Mean#getVector <em>Vector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Vector</em>'.
   * @see fr.irisa.dslCsv.Mean#getVector()
   * @see #getMean()
   * @generated
   */
  EReference getMean_Vector();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.Filter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Filter</em>'.
   * @see fr.irisa.dslCsv.Filter
   * @generated
   */
  EClass getFilter();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Filter#getFile <em>File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>File</em>'.
   * @see fr.irisa.dslCsv.Filter#getFile()
   * @see #getFilter()
   * @generated
   */
  EReference getFilter_File();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Filter#getCond <em>Cond</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cond</em>'.
   * @see fr.irisa.dslCsv.Filter#getCond()
   * @see #getFilter()
   * @generated
   */
  EReference getFilter_Cond();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.Unselect <em>Unselect</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Unselect</em>'.
   * @see fr.irisa.dslCsv.Unselect
   * @generated
   */
  EClass getUnselect();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Unselect#getFile <em>File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>File</em>'.
   * @see fr.irisa.dslCsv.Unselect#getFile()
   * @see #getUnselect()
   * @generated
   */
  EReference getUnselect_File();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Unselect#getFeatures <em>Features</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Features</em>'.
   * @see fr.irisa.dslCsv.Unselect#getFeatures()
   * @see #getUnselect()
   * @generated
   */
  EReference getUnselect_Features();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.Select <em>Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select</em>'.
   * @see fr.irisa.dslCsv.Select
   * @generated
   */
  EClass getSelect();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Select#getFile <em>File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>File</em>'.
   * @see fr.irisa.dslCsv.Select#getFile()
   * @see #getSelect()
   * @generated
   */
  EReference getSelect_File();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Select#getFeatures <em>Features</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Features</em>'.
   * @see fr.irisa.dslCsv.Select#getFeatures()
   * @see #getSelect()
   * @generated
   */
  EReference getSelect_Features();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.Save <em>Save</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Save</em>'.
   * @see fr.irisa.dslCsv.Save
   * @generated
   */
  EClass getSave();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Save#getFilename <em>Filename</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Filename</em>'.
   * @see fr.irisa.dslCsv.Save#getFilename()
   * @see #getSave()
   * @generated
   */
  EReference getSave_Filename();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Save#getFile <em>File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>File</em>'.
   * @see fr.irisa.dslCsv.Save#getFile()
   * @see #getSave()
   * @generated
   */
  EReference getSave_File();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Save#getSep <em>Sep</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sep</em>'.
   * @see fr.irisa.dslCsv.Save#getSep()
   * @see #getSave()
   * @generated
   */
  EReference getSave_Sep();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Save#getSaveHeader <em>Save Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Save Header</em>'.
   * @see fr.irisa.dslCsv.Save#getSaveHeader()
   * @see #getSave()
   * @generated
   */
  EReference getSave_SaveHeader();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Save#getSaveID <em>Save ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Save ID</em>'.
   * @see fr.irisa.dslCsv.Save#getSaveID()
   * @see #getSave()
   * @generated
   */
  EReference getSave_SaveID();

  /**
   * Returns the meta object for class '{@link fr.irisa.dslCsv.Acquire <em>Acquire</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Acquire</em>'.
   * @see fr.irisa.dslCsv.Acquire
   * @generated
   */
  EClass getAcquire();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Acquire#getPath <em>Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Path</em>'.
   * @see fr.irisa.dslCsv.Acquire#getPath()
   * @see #getAcquire()
   * @generated
   */
  EReference getAcquire_Path();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Acquire#getSep <em>Sep</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sep</em>'.
   * @see fr.irisa.dslCsv.Acquire#getSep()
   * @see #getAcquire()
   * @generated
   */
  EReference getAcquire_Sep();

  /**
   * Returns the meta object for the containment reference '{@link fr.irisa.dslCsv.Acquire#getHasHeader <em>Has Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Has Header</em>'.
   * @see fr.irisa.dslCsv.Acquire#getHasHeader()
   * @see #getAcquire()
   * @generated
   */
  EReference getAcquire_HasHeader();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DslCsvFactory getDslCsvFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.ProgramImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__EXPR = eINSTANCE.getProgram_Expr();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.ExpressionImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.AssignImpl <em>Assign</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.AssignImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getAssign()
     * @generated
     */
    EClass ASSIGN = eINSTANCE.getAssign();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSIGN__VAR = eINSTANCE.getAssign_Var();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGN__VAL = eINSTANCE.getAssign_Val();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.NopImpl <em>Nop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.NopImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getNop()
     * @generated
     */
    EClass NOP = eINSTANCE.getNop();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOP__EXPR = eINSTANCE.getNop_Expr();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.LogicalExpressionImpl <em>Logical Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.LogicalExpressionImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getLogicalExpression()
     * @generated
     */
    EClass LOGICAL_EXPRESSION = eINSTANCE.getLogicalExpression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOGICAL_EXPRESSION__LEFT = eINSTANCE.getLogicalExpression_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOGICAL_EXPRESSION__OP = eINSTANCE.getLogicalExpression_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOGICAL_EXPRESSION__RIGHT = eINSTANCE.getLogicalExpression_Right();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.CompExpressionImpl <em>Comp Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.CompExpressionImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getCompExpression()
     * @generated
     */
    EClass COMP_EXPRESSION = eINSTANCE.getCompExpression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMP_EXPRESSION__LEFT = eINSTANCE.getCompExpression_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMP_EXPRESSION__OP = eINSTANCE.getCompExpression_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMP_EXPRESSION__RIGHT = eINSTANCE.getCompExpression_Right();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.ArithExpressionImpl <em>Arith Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.ArithExpressionImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getArithExpression()
     * @generated
     */
    EClass ARITH_EXPRESSION = eINSTANCE.getArithExpression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARITH_EXPRESSION__LEFT = eINSTANCE.getArithExpression_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARITH_EXPRESSION__OP = eINSTANCE.getArithExpression_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ARITH_EXPRESSION__RIGHT = eINSTANCE.getArithExpression_Right();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.SubExpressionImpl <em>Sub Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.SubExpressionImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getSubExpression()
     * @generated
     */
    EClass SUB_EXPRESSION = eINSTANCE.getSubExpression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUB_EXPRESSION__LEFT = eINSTANCE.getSubExpression_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SUB_EXPRESSION__OP = eINSTANCE.getSubExpression_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUB_EXPRESSION__RIGHT = eINSTANCE.getSubExpression_Right();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.BaseExpressionImpl <em>Base Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.BaseExpressionImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getBaseExpression()
     * @generated
     */
    EClass BASE_EXPRESSION = eINSTANCE.getBaseExpression();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.VarImpl <em>Var</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.VarImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getVar()
     * @generated
     */
    EClass VAR = eINSTANCE.getVar();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VAR__VAR = eINSTANCE.getVar_Var();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.ConstNatImpl <em>Const Nat</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.ConstNatImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getConstNat()
     * @generated
     */
    EClass CONST_NAT = eINSTANCE.getConstNat();

    /**
     * The meta object literal for the '<em><b>Const Nat</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONST_NAT__CONST_NAT = eINSTANCE.getConstNat_ConstNat();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.ConstStrImpl <em>Const Str</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.ConstStrImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getConstStr()
     * @generated
     */
    EClass CONST_STR = eINSTANCE.getConstStr();

    /**
     * The meta object literal for the '<em><b>Const Str</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONST_STR__CONST_STR = eINSTANCE.getConstStr_ConstStr();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.ParenthesisImpl <em>Parenthesis</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.ParenthesisImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getParenthesis()
     * @generated
     */
    EClass PARENTHESIS = eINSTANCE.getParenthesis();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARENTHESIS__EXPR = eINSTANCE.getParenthesis_Expr();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.ConstVectorImpl <em>Const Vector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.ConstVectorImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getConstVector()
     * @generated
     */
    EClass CONST_VECTOR = eINSTANCE.getConstVector();

    /**
     * The meta object literal for the '<em><b>Const Vector</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONST_VECTOR__CONST_VECTOR = eINSTANCE.getConstVector_ConstVector();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.FuncCallImpl <em>Func Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.FuncCallImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getFuncCall()
     * @generated
     */
    EClass FUNC_CALL = eINSTANCE.getFuncCall();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.CountImpl <em>Count</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.CountImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getCount()
     * @generated
     */
    EClass COUNT = eINSTANCE.getCount();

    /**
     * The meta object literal for the '<em><b>Vector</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COUNT__VECTOR = eINSTANCE.getCount_Vector();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.SortImpl <em>Sort</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.SortImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getSort()
     * @generated
     */
    EClass SORT = eINSTANCE.getSort();

    /**
     * The meta object literal for the '<em><b>File</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SORT__FILE = eINSTANCE.getSort_File();

    /**
     * The meta object literal for the '<em><b>Criterion</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SORT__CRITERION = eINSTANCE.getSort_Criterion();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.DimImpl <em>Dim</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.DimImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getDim()
     * @generated
     */
    EClass DIM = eINSTANCE.getDim();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIM__EXPR = eINSTANCE.getDim_Expr();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.PrintImpl <em>Print</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.PrintImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getPrint()
     * @generated
     */
    EClass PRINT = eINSTANCE.getPrint();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRINT__EXPR = eINSTANCE.getPrint_Expr();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.FeaturesImpl <em>Features</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.FeaturesImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getFeatures()
     * @generated
     */
    EClass FEATURES = eINSTANCE.getFeatures();

    /**
     * The meta object literal for the '<em><b>File</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FEATURES__FILE = eINSTANCE.getFeatures_File();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.RowImpl <em>Row</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.RowImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getRow()
     * @generated
     */
    EClass ROW = eINSTANCE.getRow();

    /**
     * The meta object literal for the '<em><b>File</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW__FILE = eINSTANCE.getRow_File();

    /**
     * The meta object literal for the '<em><b>Vector</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW__VECTOR = eINSTANCE.getRow_Vector();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.ColumnImpl <em>Column</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.ColumnImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getColumn()
     * @generated
     */
    EClass COLUMN = eINSTANCE.getColumn();

    /**
     * The meta object literal for the '<em><b>File</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLUMN__FILE = eINSTANCE.getColumn_File();

    /**
     * The meta object literal for the '<em><b>Column Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLUMN__COLUMN_NAME = eINSTANCE.getColumn_ColumnName();

    /**
     * The meta object literal for the '<em><b>Vector</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COLUMN__VECTOR = eINSTANCE.getColumn_Vector();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.ProductImpl <em>Product</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.ProductImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getProduct()
     * @generated
     */
    EClass PRODUCT = eINSTANCE.getProduct();

    /**
     * The meta object literal for the '<em><b>Vector</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRODUCT__VECTOR = eINSTANCE.getProduct_Vector();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.SumImpl <em>Sum</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.SumImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getSum()
     * @generated
     */
    EClass SUM = eINSTANCE.getSum();

    /**
     * The meta object literal for the '<em><b>Vector</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUM__VECTOR = eINSTANCE.getSum_Vector();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.MeanImpl <em>Mean</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.MeanImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getMean()
     * @generated
     */
    EClass MEAN = eINSTANCE.getMean();

    /**
     * The meta object literal for the '<em><b>Vector</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MEAN__VECTOR = eINSTANCE.getMean_Vector();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.FilterImpl <em>Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.FilterImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getFilter()
     * @generated
     */
    EClass FILTER = eINSTANCE.getFilter();

    /**
     * The meta object literal for the '<em><b>File</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILTER__FILE = eINSTANCE.getFilter_File();

    /**
     * The meta object literal for the '<em><b>Cond</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILTER__COND = eINSTANCE.getFilter_Cond();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.UnselectImpl <em>Unselect</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.UnselectImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getUnselect()
     * @generated
     */
    EClass UNSELECT = eINSTANCE.getUnselect();

    /**
     * The meta object literal for the '<em><b>File</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNSELECT__FILE = eINSTANCE.getUnselect_File();

    /**
     * The meta object literal for the '<em><b>Features</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNSELECT__FEATURES = eINSTANCE.getUnselect_Features();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.SelectImpl <em>Select</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.SelectImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getSelect()
     * @generated
     */
    EClass SELECT = eINSTANCE.getSelect();

    /**
     * The meta object literal for the '<em><b>File</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT__FILE = eINSTANCE.getSelect_File();

    /**
     * The meta object literal for the '<em><b>Features</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT__FEATURES = eINSTANCE.getSelect_Features();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.SaveImpl <em>Save</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.SaveImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getSave()
     * @generated
     */
    EClass SAVE = eINSTANCE.getSave();

    /**
     * The meta object literal for the '<em><b>Filename</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SAVE__FILENAME = eINSTANCE.getSave_Filename();

    /**
     * The meta object literal for the '<em><b>File</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SAVE__FILE = eINSTANCE.getSave_File();

    /**
     * The meta object literal for the '<em><b>Sep</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SAVE__SEP = eINSTANCE.getSave_Sep();

    /**
     * The meta object literal for the '<em><b>Save Header</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SAVE__SAVE_HEADER = eINSTANCE.getSave_SaveHeader();

    /**
     * The meta object literal for the '<em><b>Save ID</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SAVE__SAVE_ID = eINSTANCE.getSave_SaveID();

    /**
     * The meta object literal for the '{@link fr.irisa.dslCsv.impl.AcquireImpl <em>Acquire</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.irisa.dslCsv.impl.AcquireImpl
     * @see fr.irisa.dslCsv.impl.DslCsvPackageImpl#getAcquire()
     * @generated
     */
    EClass ACQUIRE = eINSTANCE.getAcquire();

    /**
     * The meta object literal for the '<em><b>Path</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACQUIRE__PATH = eINSTANCE.getAcquire_Path();

    /**
     * The meta object literal for the '<em><b>Sep</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACQUIRE__SEP = eINSTANCE.getAcquire_Sep();

    /**
     * The meta object literal for the '<em><b>Has Header</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACQUIRE__HAS_HEADER = eINSTANCE.getAcquire_HasHeader();

  }

} //DslCsvPackage
