/**
 * generated by Xtext 2.25.0
 */
package fr.irisa.dslCsv;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logical Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.irisa.dslCsv.LogicalExpression#getLeft <em>Left</em>}</li>
 *   <li>{@link fr.irisa.dslCsv.LogicalExpression#getOp <em>Op</em>}</li>
 *   <li>{@link fr.irisa.dslCsv.LogicalExpression#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see fr.irisa.dslCsv.DslCsvPackage#getLogicalExpression()
 * @model
 * @generated
 */
public interface LogicalExpression extends Expression
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(CompExpression)
   * @see fr.irisa.dslCsv.DslCsvPackage#getLogicalExpression_Left()
   * @model containment="true"
   * @generated
   */
  CompExpression getLeft();

  /**
   * Sets the value of the '{@link fr.irisa.dslCsv.LogicalExpression#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(CompExpression value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see fr.irisa.dslCsv.DslCsvPackage#getLogicalExpression_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link fr.irisa.dslCsv.LogicalExpression#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(LogicalExpression)
   * @see fr.irisa.dslCsv.DslCsvPackage#getLogicalExpression_Right()
   * @model containment="true"
   * @generated
   */
  LogicalExpression getRight();

  /**
   * Sets the value of the '{@link fr.irisa.dslCsv.LogicalExpression#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(LogicalExpression value);

} // LogicalExpression
